### ISSUE TITLE
[BUG] Trying to fetch internal txns yields AssertionError if there are no internal txns

### ISSUE THREAD

**Issue by putzwasser** [pcko1/bscscan-python#30]
**Describe the bug**
Trying to fetch internal txns yields AssertionError if there are no internal txns

**To Reproduce**
Fetch blocks which do not have internal txns for a given account

**Expected behavior**
Return of an empty list. The docs said that the functions returns a list of dicts. So, if there are no txns I'd expect to return an empty list instead of yielding an error. Is that desired behaviour?

**Additional context**
```
Traceback (most recent call last):
  File "bscscan-import.py", line 190, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "bscscan-import.py", line 77, in main
    internal_txns = await bsc.get_internal_txs_by_address(
  File "~/lib/python3.9/site-packages/bscscan/core/async_client.py", line 27, in wrapper
    return parser.parse(await response.json())
  File "~/.local/lib/python3.9/site-packages/bscscan/utils/parsing.py", line 11, in parse
    assert status, f"{result} -- {message}"
AssertionError: [] -- No transactions found
```

**Comment by pcko1** [comment]
Kindly refer to this [old issue](https://github.com/pcko1/bscscan-python/issues/9#issuecomment-845409509). 

In short, BscScan returns a status code of 0 when there are no txs, which in turn is handled as an exception.
